### ISSUE TITLE
There should be a long_description in the package metadata

### ISSUE THREAD

**Issue by funkyfuture** [gabrielcnr/pytest-datadir#16]
[this](https://pypi.org/project/pytest-datadir/) doesn't look as promising as it actually is atm.

**Comment by funkyfuture** [comment]
ah, sorry for my unverbosity. i just wanted to point out that the project page on the PyPI promises nothing. while saying that the plugin is promising would rather be an understatement.

**Comment by nicoddemus** [comment]
Oh I see, thanks for the clarification. 

We should use the contents of `README.md` for the long description, fortunately now [PyPI supports markdown](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi):

```
setup(
    ...
    long_description=long_description,
    long_description_content_type="text/markdown",
)
```

@funkyfuture perhaps you would like to contribute a PR?
