### ISSUE TITLE
Failed to reference from session/module scope

### ISSUE THREAD

**Issue by bcho** [gabrielcnr/pytest-datadir#26]
Hi, it seems that the plugin fixtures' default scope is `function`, when I try to reference the fixture from a fixture with `session` scope, py.test will raise a  `ScopeMismatch` error.

My use case is:

1. put a database schema init sql file to the data dir
2. add a fixture call `init_db`, which has `session` scope, and it will recreate the database schema only once during the whole test execution
3. `init_db` fixture use `shared_datadir` to read the init sql file

Any suggestions for this use case? Or can we change the plugin fixtures scope to `session` (or something else)?

**Comment by bcho** [comment]
After checking the code, it seems like the plugin requires reading dir from `request.fspath`, which is unavailable in session-scoped context... :crying_cat_face:

**Comment by nicoddemus** [comment]
Hi @bcho,

`datadir` is meant to be used for every test.

For your use case, doesn't seem like you need `datadir` at all. Can't you use the builtin [`tmp_path_factory`](https://docs.pytest.org/en/latest/reference.html#tmp-path-factory) instead?

**Comment by bcho** [comment]
@nicoddemus Understood! I solved my problem by extracting from current working dir from `__file__`. Thanks for your help :+1:
