### ISSUE TITLE
Change license to MIT?

### ISSUE THREAD

**Issue by nicoddemus** [gabrielcnr/pytest-datadir#3]
Unfortunately LGPL brings a number of problems for some people/organizations:

From pytest-dev/pytest-mock#45:

> I can't use any form of GPL at work (including LGPL). Even if it was possible, the handling considerations wouldn't be worth it for a plugin. A few months ago I had a remote worker try to borrow code from an LGPL plugin for a project, thinking "hey it's open source, and freedom". Its not easy to convey the ramification of creating a derivative work.

> pytest itself is MIT.

What do you think about changing the license of this plugin to MIT?

**Comment by gabrielcnr** [comment]
Closed by 7396f9e
