### ISSUE TITLE
A way to update files in datadir automatic

### ISSUE THREAD

**Issue by alissonperez** [gabrielcnr/pytest-datadir#32]
Just a suggestion, I'm always had a little bit of work to update files in the shared data dirs. Do you think in a way to update files?

I used sometimes `jest` with snapshots it has a very good way to update snapshot files. Maybe we could implement something in this way, what do you think? https://jestjs.io/docs/en/snapshot-testing#updating-snapshots

Tks!!

**Comment by greschd** [comment]
You might want to check out ``pytest-regressions`` https://github.com/ESSS/pytest-regressions, which uses ``pytest-datadir`` under the hood.

**Comment by nicoddemus** [comment]
Yeah, updating the files in the data-dir usually is tied on how to generate the data files, which varies a lot. I'm afraid this is out of scope of this plugin.

ESSS/pytest-regressions is an example of a plugin which does something similar to what you want.
