### ISSUE TITLE
Remove usage of tmpdir

### ISSUE THREAD

**Issue by kasium** [gabrielcnr/pytest-datadir#48]
According to pytest tmpdir is deprecated and should be replaced with tmp_path. Would you be open for a PR to change this?

**Comment by nicoddemus** [comment]
Definitely would be appreciated, thanks!

**Comment by kasium** [comment]
@nicoddemus would you please consider to push a release?

**Comment by nicoddemus** [comment]
Done: https://github.com/gabrielcnr/pytest-datadir/pull/51
