### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by edisongustavo** [gabrielcnr/pytest-datadir#5]
It would be great If the repo could be tagged so that we have versions for each release.

**Comment by nicoddemus** [comment]
@gabrielcnr could you please add me as maintainer on PyPI (my user name is `nicoddemus`)? I would like to be able to make releases as well. :grin:

**Comment by gabrielcnr** [comment]
@nicoddemus Done!

**Comment by nicoddemus** [comment]
@gabrielcnr is `0.1` at 9fbc9e65fb? We should push that tag then.

**Comment by nicoddemus** [comment]
Pushed the `0.1.0` tag at 9fbc9e6.
