### ISSUE TITLE
Release 1.0?

### ISSUE THREAD

**Issue by nicoddemus** [gabrielcnr/pytest-datadir#7]
I just noticed that we set the [Development Status to Production](https://github.com/gabrielcnr/pytest-datadir/blob/master/setup.py#L28), but have not released 1.0 yet. My question is:

@gabrielcnr do you see still think the API might change? If so, we should probably change the Development Status to Alpha or Beta. If not, we should probably release 1.0 and promise backward compatibility, at least until 2.0 is released.

**Comment by gabrielcnr** [comment]
@nicoddemus No, I don't think the current API will change in the future. I wanted to add more features, enhance with a few convenience methods. For example, I think we need a method to "write to original location". This is going to be useful on the cases when you need to update your test baseline. Also it would be nice to have some convenience methods to `datadir.read(filename)` which already reads and returns the file's full contents, a `datadir.listdir()` which would be a shorthand for `import os` followed by `os.listdir(datadir.global_dir)` or why not even making the datadir object iterable over its files?
All these changes would be additions to the existing API, which I can't see changing (accessing files via `datadir[filename]`).
So from my POV, I think we can tag 1.0 and mark as the official release?

**Comment by nicoddemus** [comment]
@gabrielcnr I see. If you are planning these convenience methods, then I urge you to instead change the interface and make `datadir` return a [`Path`](https://docs.python.org/3/library/pathlib.html#concrete-paths) object instead. It has several advantages over re-implementing the methods you mention:

1. It is part of the standardlib since 3.4, with a [pypi](https://pypi.python.org/pypi/pathlib/) backport which supports Python 2.6 and later. 
2. Contains all the methods you listed, and many more.

This would meant the current way of using `datadir` would have to break:

```python
def test(datadir):
    f = datadir['file.txt']
```

Would become:

```python
def test(datadir):
    f = datadir.joinpath('file.txt')
```

But on the other hand there's a lot of operations which makes things more convenient:

```python
def test(datadir):
    first_txt_file = datadir.glob('*.txt')[0]
    contents = first_txt_file.read_text()
```

**Comment by gabrielcnr** [comment]
@nicoddemus I agree with your idea. What do you think about still maintaining the nice/current API by subclassing `Path` and overriding `__getitem__`?

**Comment by nicoddemus** [comment]
Don't think it is worth it, to be honest... specially because we can break backward compatibility at this point. Otherwise we will have to carry that "special case" onward in the 1.0 series.
